# Generated by Django 5.0.6 on 2024-06-26 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_delete_image_alter_product_name_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='image_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='myapp.imageclassification'),
        ),
    ]
